### register
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}

### login
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}

> {% client.global.set("auth_token", response.body.access_token); %}

### protected
GET http://localhost:5000/protected
Authorization: Bearer {{auth_token}}

#### Sem token
GET http://localhost:5000/protected
#Authorization: Bearer {{auth_token}}

#### token inválido
GET http://localhost:5000/protected
Authorization: Bearer {{auth_token}}123

### Receipt

#### Receipt Create
POST http://localhost:5000/recipes
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Feijoada",
  "ingredients": "Feijão preto, carne de porco, linguiçã calabresa, temperos",
  "time_minutes": 120
}

#### Receipt List
GET http://localhost:5000/recipes

### Receipt Patch
PATCH localhost:5000/recipes/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "Feijoada Atualizada"
}

### Receipt Delete
DELETE localhost:5000/recipes/1
Authorization: Bearer {{auth_token}}