import doc_string_exemplo
import doc_string_classe_exemplo

print('DIR')
print(dir(doc_string_exemplo))
print('__DOC__')
print(doc_string_exemplo.__doc__)
print('__FILE__')
print(doc_string_exemplo.__file__)
print('__LOADER__')
print(doc_string_exemplo.__loader__)
print('__NAME__')
print(doc_string_exemplo.__name__)
print('__PACKAGE__')
print(doc_string_exemplo.__package__)
print('__SPEC__')
print(doc_string_exemplo.__spec__)
print('')

print(dir(doc_string_classe_exemplo))
print('__DOC__')
print(doc_string_classe_exemplo.__doc__)
print('__FILE__')
print(doc_string_classe_exemplo.__file__)
print('__LOADER__')
print(doc_string_classe_exemplo.__loader__)
print('__NAME__')
print(doc_string_classe_exemplo.__name__)
print('__PACKAGE__')
print(doc_string_classe_exemplo.__package__)
print('__SPEC__')
print(doc_string_classe_exemplo.__spec__)
print('')

print('HELP')
print(help(doc_string_exemplo))
print(help(doc_string_classe_exemplo))