"""Adiciona coluna date_de_nascimento

Revision ID: 9df388adc3c2
Revises: 108a33706071
Create Date: 2025-09-11 19:45:58.784665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9df388adc3c2"
down_revision: Union[str, Sequence[str], None] = "108a33706071"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usuarios", sa.Column("data_de_nascimento", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuarios", "data_de_nascimento")
    # ### end Alembic commands ###
